$schema: 'https://moonrepo.dev/schemas/tasks.json'

implicitDeps:
  - '^:build'

implicitInputs:
  - 'package.json'

fileGroups:
  configs:
    - '*.{js,mjs,json}'

  sources:
    - 'src/**/*'
    - 'types/**/*'

  tests:
    - 'tests/**/*.test.*'

  stories:
    - '.storybook/**/*'
    - 'stories/**/*.stories.*'

  styles:
    - '**/*.{scss,css}'

  assets:
    - 'assets/**/*'
    - 'images/**/*'
    - 'static/**/*'
    - '**/*.{scss,css}'
    - '**/*.mdx'

  typescript:
    - 'tsconfig.json'
    - 'tsconfig.*.json'
    - '/tsconfig.json'
    - '/tsconfig.*.json'

tasks:
  format:
    command: 'prettier'
    args:
      - '--config'
      - '@in(1)'
      - '--ignore-path'
      - '@in(0)'
      - '--check'
      - '.'
    inputs:
      - '/.prettierignore'
      - '/.prettierrc.js'
      - '@globs(configs)'
      - '@globs(sources)'
      - '@globs(stories)'
      - '@globs(tests)'
      - '**/*.{md,mdx,yml,yaml,json}'

  format-write:
    command: 'prettier'
    args:
      - '--config'
      - '@in(1)'
      - '--ignore-path'
      - '@in(0)'
      - '--write'
      - '.'
    inputs:
      - '/.prettierignore'
      - '/.prettierrc.js'
      - '@globs(configs)'
      - '@globs(sources)'
      - '@globs(tests)'
      - '**/*.{md,mdx,yml,yaml,json}'
    options:
      runInCI: false

  lint:
    command: 'eslint'
    args:
      - '--ext'
      - '.js,.jsx,.ts,.tsx'
      - '--fix'
      - '--report-unused-disable-directives'
      - '--no-error-on-unmatched-pattern'
      - '--exit-on-fatal-error'
      - '--ignore-path'
      - '@in(7)'
      - '.'
    inputs:
      - '@globs(configs)'
      - '@globs(sources)'
      - '@globs(stories)'
      - '@globs(tests)'
      - '@globs(typescript)'
      - '**/.eslintrc'
      - '**/.eslintrc.*'
      - '/.eslintignore'
      - '/.eslintrc.*'
    options:
      affectedFiles: true

  stylelint:
    command: 'stylelint'
    args:
      - '--config'
      - '@in(1)'
      - '--ignore-path'
      - '@in(0)'
    inputs:
      - '/.stylelintignore'
      - '/.stylelintrc.js'
      - '@globs(styles)'
      - '**/*.{css,scss}'
    options:
      affectedFiles: true

  test:
    command: 'jest'
    args:
      - '--passWithNoTests'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'
      - '.babelrc'
      - '.babelrc.*'
      - 'babel.config.*'
      - 'jest.config.*'
      - '/babel.config.*'

  typecheck:
    command: 'tsc'
    args:
      - '--build'
      - '--pretty'
    inputs:
      - '@globs(sources)'
      - '@globs(stories)'
      - '@globs(tests)'
      - '@globs(typescript)'
